"""rename rfid_tag to book_code

Revision ID: 28fa2d7f5a63
Revises: f3981894f362
Create Date: 2025-12-18 15:07:44.418291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fa2d7f5a63'
down_revision: Union[str, Sequence[str], None] = 'f3981894f362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_instance', sa.Column('book_code', sa.String(), nullable=False))
    op.drop_constraint(op.f('book_instance_rfid_tag_key'), 'book_instance', type_='unique')
    op.create_unique_constraint(None, 'book_instance', ['book_code'])
    op.drop_column('book_instance', 'rfid_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_instance', sa.Column('rfid_tag', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book_instance', type_='unique')
    op.create_unique_constraint(op.f('book_instance_rfid_tag_key'), 'book_instance', ['rfid_tag'], postgresql_nulls_not_distinct=False)
    op.drop_column('book_instance', 'book_code')
    # ### end Alembic commands ###
