"""rename rfid_tag to book_code

Revision ID: 28fa2d7f5a63
Revises: f3981894f362
Create Date: 2025-12-18 15:07:44.418291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fa2d7f5a63'
down_revision: Union[str, Sequence[str], None] = 'f3981894f362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Явно указываем имя констрейнта, который удаляем
    op.drop_constraint('book_instance_rfid_tag_key', 'book_instance', type_='unique')
    op.alter_column('book_instance', 'rfid_tag', new_column_name='book_code')
    # Явно задаем имя для нового констрейнта
    op.create_unique_constraint('book_instance_book_code_key', 'book_instance', ['book_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('book_instance_book_code_key', 'book_instance', type_='unique')
    op.alter_column('book_instance', 'book_code', new_column_name='rfid_tag')
    op.create_unique_constraint('book_instance_rfid_tag_key', 'book_instance', ['rfid_tag'])
    # ### end Alembic commands ###
