"""add user relation in transaction

Revision ID: 971a6058000c
Revises: 82875e768a97
Create Date: 2025-12-10 02:09:31.671144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '971a6058000c'
down_revision: Union[str, Sequence[str], None] = '82875e768a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'user_id')
    # ### end Alembic commands ###
