"""add pickup_code to reservation

Revision ID: de652cc86d5b
Revises: 971a6058000c
Create Date: 2025-12-13 16:15:26.909762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de652cc86d5b'
down_revision: Union[str, Sequence[str], None] = '971a6058000c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('pickup_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'pickup_code')
    # ### end Alembic commands ###
