"""add qr_code_url

Revision ID: f3981894f362
Revises: de652cc86d5b
Create Date: 2025-12-13 19:32:22.796882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3981894f362'
down_revision: Union[str, Sequence[str], None] = 'de652cc86d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('qr_code_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'qr_code_url')
    # ### end Alembic commands ###
